=== 27-TRM-02/RecetasFinal/xml-resources/jaxb/recetas_binding/recetas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="recetas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="tipo">
                                <xs:complexType>
                                    <xs:attribute name="definicion" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="dificultad" type="xs:string" />
                            <xs:element name="calorias" type="xs:string" />
                            <xs:element name="tiempo" type="xs:string" />
                            <xs:element name="elaboracion" type="xs:string" />
                            <xs:element name="ingredientes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingrediente" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="cantidad" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 27-TRM-02/RecetasFinal/recetas.xml
<?xml version="1.0" encoding="utf-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="recetas.xsd">
    <receta id="1">
        <nombre>Tarta de chocolate</nombre>
        <tipo definicion="postre"/>
        <dificultad>Fácil</dificultad>
        <calorias>600</calorias>
        <tiempo>45 minutos</tiempo>
        <elaboracion>Horno</elaboracion>
        <ingredientes>
            <ingrediente cantidad="250 gramos">
                Cola-Cao
            </ingrediente>
            <ingrediente cantidad="200 gramos">
                Mantequilla
            </ingrediente>
            <ingrediente cantidad="1 vaso">
                Harina
            </ingrediente>
            <ingrediente cantidad="1 vaso">
                Azúcar
            </ingrediente>
            <ingrediente cantidad="3">
                Huevos
            </ingrediente>
        </ingredientes>
    </receta>
    <receta id="2">
        <nombre>Tiramisú</nombre>
        <tipo definicion="postre"/>
        <dificultad>Media</dificultad>
        <calorias>450</calorias>
        <tiempo>7 horas</tiempo>
        <elaboracion>Microondas</elaboracion>
        <ingredientes>
            <ingrediente cantidad="24">
                Bizcochos blandos
            </ingrediente>
            <ingrediente cantidad="100 gramos">
                Cobertura valor
            </ingrediente>
            <ingrediente cantidad="0.5 vaso">
                Azúcar
            </ingrediente>
            <ingrediente cantidad="1 tazon">
                Café solo
            </ingrediente>
            <ingrediente cantidad="3">
                Huevos
            </ingrediente>
            <ingrediente cantidad="Muy poco; al gusto">
                Licor
            </ingrediente>
            <ingrediente cantidad="0.3 litros">
                Nata líquida
            </ingrediente>
            <ingrediente cantidad="250 gramos">
                Queso mascarpone
            </ingrediente>
        </ingredientes>
    </receta>
</recetas>
